apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-avp-enabled-application
  namespace: argocd
spec:
  destination:
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: example/example-app/
    repoURL: https://github.com/westelh/argocd.git
    targetRevision: HEAD
    plugin:
      env:
        - name: 
  project: default
