kind: Secret
apiVersion: v1
metadata:
  name: vault-example
  annotations:
    avp.kubernetes.io/path: "kv/data/example"
type: Opaque
data:
  username: <username | base64encode>
  password: <password | base64encode>
